//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BigBrother.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_TRAYICON                    101
#define IDD_PROPS_SETTINGS              102
#define ID_PINGBAR                      102
#define IDD_PROPS_GENERAL               103
#define TM_CHECK                        103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_PROPS_ACTION                104
#define IDS_PROPS_TITLE                 105
#define IDS_LOG_DOLOG                   106
#define IDS_LOG_DONTLOG                 107
#define IDS_LOG_ASKBIGBROTHER           108
#define IDS_NODESC                      109
#define IDS_PS_FAILEDTORESOLVE          110
#define IDS_PS_UNABLETOICMP             111
#define IDS_PS_INTERNALERROR            112
#define IDS_PS_NETUNREACHABLE           113
#define IDS_PS_HOSTUNREACHABLE          114
#define IDS_PS_PROTUNREACHABLE          115
#define IDS_PS_PORTUNREACHABLE          116
#define IDS_PS_NORESOURCES              117
#define IDS_PS_HWERROR                  118
#define IDS_PS_BIGPACKET                119
#define IDS_PS_TIMEOUT                  120
#define IDS_PS_BADROUTE                 121
#define IDS_PS_TTLEXPTRANSIT            122
#define IDS_PS_TTLEXPREASM              123
#define IDS_PS_IPARAMP                  124
#define IDS_PS_SOURCEQUENCH             125
#define IDS_PS_BIGOPTION                126
#define IDS_PS_BADDEST                  127
#define IDR_MAINFRAME                   128
#define IDR_BIGBROTYPE                  129
#define IDS_PS_UNKNOWNERROR             129
#define IDS_REGISTRYKEY                 130
#define IDI_NOHOST                      131
#define IDS_AVIEW_NOTIP                 131
#define IDI_PENDING                     132
#define IDS_AVIEW_SHORTTIP              132
#define IDI_HOST                        133
#define IDM_POPUPS                      133
#define IDS_AVIEW_TIP_TIMEFORMAT        133
#define IDI_PINGING                     134
#define IDR_PINGBAR                     134
#define IDS_AVIEW_TIP_UNPINGED          134
#define IDI_GOINGDOWN                   135
#define IDR_JUNKACCELERATOR             135
#define IDS_AVIEW_TIP_UNREACHABLE       135
#define IDI_HOSTDOWN                    136
#define IDR_JUNKTOOLBAR                 136
#define IDS_AVIEW_TIP_RTTREPORT         136
#define IDS_ROOTNODENAME                137
#define IDS_WAVFILTER                   138
#define IDW_HOST_UP                     138
#define IDW_HOST_DOWN                   139
#define IDS_ACTION_HOST_UP              139
#define IDS_ACTION_HOST_DOWN            140
#define IDI_PREPLAY                     140
#define IDI_BROWSESOUND                 141
#define IDD_PREFS                       141
#define IDS_LOGFILTER                   141
#define IDS_LOG_HOSTUP                  142
#define IDS_LOG_HOSTDOWN                143
#define IDS_LOG_DATEFORMAT              144
#define IDS_LOGFILE_SELECT              145
#define IDS_SOUND_SELECT                146
#define IDS_LOG_LOADFILE                147
#define IDS_ACTION_SYSTEM_OK            148
#define IDS_ACTION_SYSTEM_CRITICAL      149
#define IDC_OVERRIDE_INTERVALS          1000
#define IDC_PINGINTERVAL_GOOD           1001
#define IDC_PINGINTERVAL_BAD            1002
#define IDC_OVERRIDE_TIMEOUT            1003
#define IDC_PINGTIMEOUT                 1004
#define IDC_HOST                        1004
#define IDC_OVERRIDE_RETRIES            1005
#define IDC_DESC                        1005
#define IDC_RETRIES                     1006
#define IDC_LOG_ACTIVITY                1006
#define IDC_OVERRIDE_ACTION             1010
#define IDC_PLAYASOUND_DOWN             1011
#define IDC_SOUND_DOWN                  1012
#define IDC_PLAYASOUND_UP               1013
#define IDC_CUSTOM_DOWN                 1014
#define IDC_PROGRAM_DOWN                1015
#define IDC_SOUND_UP                    1016
#define IDC_CUSTOM_UP                   1017
#define IDC_PROGRAM_UP                  1018
#define IDC_KLEVERNET                   1018
#define IDC_PREVIEW_SOUND_UP            1020
#define IDC_PREVIEW_SOUND_DOWN          1021
#define IDC_SAVEONSHUTDOWN              1021
#define IDC_BROWSE_SOUND_UP             1022
#define IDC_AUTOSAVEMINS                1022
#define IDC_BROWSE_SOUND_DOWN           1023
#define IDC_AUTOSPIN                    1023
#define IDC_PINGSIZE                    1024
#define IDC_DATASIZESPIN                1025
#define IDC_MAXTHREADS                  1026
#define IDC_THREADSPIN                  1027
#define IDC_LOGFILE                     1028
#define IDC_BROWSE                      1029
#define IDC_LOGMINS                     1030
#define IDC_LOGMINSPIN                  1032
#define IDC_STOREACTIVITY               1033
#define ID_BROTHERS_NEW                 32771
#define ID_VIEW_MAINWINDOW              32773
#define ID_INDICATOR_PINGBAR            32775
#define ID_BROTHERS_ADDBROTHER          32776
#define ID_BROTHERS_DELETE              32777
#define ID_FILE_AUTOLOAD                32782
#define ID_FILE_PREFERENCES             32783
#define ID_FILE_PAUSE                   32784
#define ID_VIEW_HOSTPROPERTIES          32789
#define ID_HELP_LEGEND                  32791

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32795
#define _APS_NEXT_CONTROL_VALUE         1034
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
